### ISSUE TITLE
How to fill event form ?

### ISSUE THREAD

**Issue by blockChn** [ProofOfToss/proof-of-toss#2]
![image](https://user-images.githubusercontent.com/3413744/40913799-5521ca22-6813-11e8-8d58-12aafb7bcd6d.png)

I am trying to create new even from admin page. Not sure what to fill to create it. Please provide help on it.

**Comment by aleksandrborodulin** [comment]
Hello @asifzuddin. Thank you for your question.

Insert a link or text in the field Source Url, so that users can find a result of the event there. Then press button "Add new". You should add at least one source.

In the field **Results** you should add two or more results. Fill the text field and press "Add new" button. For example:
- **Yes**, **No**
- **Win**, **Loose**, **Goalless draw**

Do you have problems with other fields?

**Comment by blockChn** [comment]
Hey @axiomaborodulin  @epavlenko ,  thanks for response. 
I can now create event successfully. But cannot see the bet on the play screen. 
**What need to be done to see the bets ?**
Even waited for 20 mins , till the start time of the bets .

![image](https://user-images.githubusercontent.com/3413744/40921692-cee27838-682d-11e8-8753-f64db93cbd51.png)

![image](https://user-images.githubusercontent.com/3413744/40921699-d481cd8e-682d-11e8-897f-c41d2d5594e0.png)

**Comment by blockChn** [comment]
elasticsearch resolved this.
