### ISSUE TITLE
Elastic search

### ISSUE THREAD

**Issue by blockChn** [ProofOfToss/proof-of-toss#3]
I have done setup on ubuntu virtual box. And Elastic search is not installed on my machine.
http://elasticsearch:9200 is not working.

Will this affect creation of bets thru admin page and viewing of bet ?

**Comment by blockChn** [comment]
@n-savchenko can you please help on this ?

**Comment by n-savchenko** [comment]
Hello @asifzuddin. Thank you for your question.

You need to run elasticsearch server to get site work. New events sends directly to blockchain so elasticsearch is not affect the events creation. But events and bets must be indexed in elasticsearch in order to show up on site. So yes, elasticsearch affect viewing.

There is a docker-compose.yml file with elasticsearch in the project root. You could try it, but we didn't tested it yet because we use AWS Elasticsearch service for development and MVP.

**Comment by blockChn** [comment]
@n-savchenko thank you.
I have elasticsearch running at : http://localhost:9200/ and configured it at /proof-of-toss/kibana.yml.
Is this much enough to connect to elastcisearch ?

**Comment by n-savchenko** [comment]
I just noticed that src/util/esClient.js have hardcoded AWS url and changes should be done in code in order to use other than AWS elasticsearch. We'll fix it today.

**Comment by blockChn** [comment]
@n-savchenko  Many thanks for checking. 
Waiting for your response .

**Comment by blockChn** [comment]
@n-savchenko  I see few commits related to AWS today , are those related to the above issue ?

**Comment by n-savchenko** [comment]
Here is a commit fixing that issue 5a25501fcb59e52892fbe2bbacea31ac8497fca9
Now you can write "http://localhost:9200/" to elasticsearch.esNode at src/data/config.json and it should work.

You need to run `babel-node scripts/create_es_index.js` to create an elasticsearch index. And then run `babel-node scripts/app.js` to watch for the events and bets and index them.

**Comment by blockChn** [comment]
@n-savchenko  thank you...
